# Generated by Django 4.2.7 on 2025-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('jenis_surat', models.CharField(choices=[('domisili', 'Surat Domisili'), ('sktm', 'Surat Keterangan Tidak Mampu'), ('usaha', 'Surat Keterangan Usaha')], max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Diproses', max_length=20)),
            ],
        ),
    ]
