# Generated by Django 4.2.7 on 2025-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('alamat', models.CharField(max_length=100)),
                ('jenis_surat', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('siap', 'Siap Diambil')], default='diajukan', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
