# Generated by Django 4.2.7 on 2025-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('domisili', 'Surat Domisili'), ('sktm', 'Surat Keterangan Tidak Mampu'), ('usaha', 'Surat Keterangan Usaha')], max_length=20),
        ),
    ]
