# Generated by Django 4.2.7 on 2025-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktakelahiran',
            name='hasil_surat',
            field=models.FileField(blank=True, null=True, upload_to='hasil_surat/akta_kematian/'),
        ),
        migrations.AddField(
            model_name='aktakematian',
            name='hasil_surat',
            field=models.FileField(blank=True, null=True, upload_to='hasil_surat/akta_kematian/'),
        ),
        migrations.AddField(
            model_name='pindahdatang',
            name='hasil_surat',
            field=models.FileField(blank=True, null=True, upload_to='hasil_surat/akta_kematian/'),
        ),
        migrations.AddField(
            model_name='pindahkeluar',
            name='hasil_surat',
            field=models.FileField(blank=True, null=True, upload_to='hasil_surat/akta_kematian/'),
        ),
    ]
