# Generated by Django 4.2.7 on 2025-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0002_remove_announcement_image_announcementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skupengajuan',
            name='surat_kuasa',
            field=models.ImageField(blank=True, null=True, upload_to='SKU/surat_kuasa/'),
        ),
    ]
