# Generated by Django 4.2.7 on 2025-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0002_alter_pengajuansurat_jenis_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktaKelahiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AktaKematian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenazah', models.CharField(max_length=100)),
                ('nik_jenazah', models.CharField(max_length=16)),
                ('tanggal_kematian', models.DateField()),
                ('tempat_kematian', models.CharField(max_length=100)),
                ('penyebab_kematian', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_pelapor', models.CharField(max_length=100)),
                ('nik_pelapor', models.CharField(max_length=16)),
                ('hubungan_pelapor', models.CharField(max_length=100)),
                ('kk_jenazah', models.FileField(blank=True, null=True, upload_to='akta_kematian/')),
                ('ktp_jenazah', models.FileField(blank=True, null=True, upload_to='akta_kematian/')),
                ('surat_keterangan_kematian', models.FileField(blank=True, null=True, upload_to='akta_kematian/')),
                ('surat_keterangan_rs', models.FileField(blank=True, null=True, upload_to='akta_kematian/')),
                ('dokumen_pendukung_lainnya', models.FileField(blank=True, null=True, upload_to='akta_kematian/')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
            ],
        ),
    ]
