# Generated by Django 4.2.7 on 2025-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomisiliPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('no_whatsapp', models.CharField(max_length=15)),
                ('surat_pengantar', models.FileField(upload_to='domisili/surat_pengantar/')),
                ('foto_ktp', models.ImageField(upload_to='domisili/foto_ktp/')),
                ('foto_kk', models.ImageField(upload_to='domisili/foto_kk/')),
                ('surat_permohonan', models.FileField(upload_to='domisili/surat_permohonan/')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20)),
                ('hasil_surat', models.FileField(blank=True, null=True, upload_to='domisili/hasil_surat/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKTMPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('no_whatsapp', models.CharField(max_length=15)),
                ('surat_pengantar', models.FileField(upload_to='sktm/surat_pengantar/')),
                ('foto_ktp', models.ImageField(upload_to='sktm/foto_ktp/')),
                ('foto_kk', models.ImageField(upload_to='sktm/foto_kk/')),
                ('surat_pernyataan', models.FileField(upload_to='sktm/surat_pernyataan/')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20)),
                ('hasil_surat', models.FileField(blank=True, null=True, upload_to='sktm/hasil_surat/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('no_whatsapp', models.CharField(max_length=15)),
                ('npwp', models.CharField(max_length=50)),
                ('surat_pengantar', models.FileField(upload_to='SKU/surat_pengantar/')),
                ('surat_permohonan', models.FileField(upload_to='SKU/surat_permohonan/')),
                ('foto_ktp', models.ImageField(upload_to='SKU/foto_ktp/')),
                ('foto_kk', models.ImageField(upload_to='SKU/foto_kk/')),
                ('surat_kuasa', models.ImageField(upload_to='SKU/surat_kuasa/')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20)),
                ('hasil_surat', models.FileField(blank=True, null=True, upload_to='SKU/hasil_surat/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
