# Generated by Django 4.2.7 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0003_aktakelahiran_aktakematian'),
    ]

    operations = [
        migrations.CreateModel(
            name='PindahDatang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('asal_daerah', models.CharField(max_length=100)),
                ('tujuan_daerah', models.CharField(max_length=100)),
                ('tanggal_pindah', models.DateField()),
                ('alasan_pindah', models.TextField()),
                ('kk_lama', models.FileField(upload_to='pindah_datang/kk_lama/')),
                ('ktp', models.FileField(upload_to='pindah_datang/ktp/')),
                ('surat_pengantar', models.FileField(upload_to='pindah_datang/surat_pengantar/')),
            ],
        ),
        migrations.CreateModel(
            name='PindahKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('asal_daerah', models.CharField(max_length=100)),
                ('tujuan_daerah', models.CharField(max_length=100)),
                ('tanggal_pindah', models.DateField()),
                ('alasan_pindah', models.TextField()),
                ('kk', models.FileField(upload_to='pindah_keluar/kk/')),
                ('ktp', models.FileField(upload_to='pindah_keluar/ktp/')),
                ('surat_pengantar', models.FileField(upload_to='pindah_keluar/surat_pengantar/')),
            ],
        ),
    ]
