# Generated by Django 4.2.7 on 2025-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0003_alter_skupengajuan_surat_kuasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skupengajuan',
            name='npwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
