# Generated by Django 4.2.7 on 2025-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0004_alter_skupengajuan_npwp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktakelahiran',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='aktakematian',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=10),
        ),
        migrations.AlterField(
            model_name='domisilipengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='pindahdatang',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='pindahkeluar',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sktmpengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='skupengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses'), ('ditolak', 'Persyaratan Tidak Terpenuhi')], default='diajukan', max_length=20),
        ),
    ]
